-- ROWNUM 사용
SELECT NAME
FROM (
    SELECT NAME
    FROM ANIMAL_INS
    ORDER BY DATETIME ASC
)
WHERE ROWNUM = 1
;

-- RANK() 함수 사용
SELECT NAME
FROM (
        SELECT RANK() OVER (ORDER BY DATETIME ASC) RANK
              ,NAME
        FROM ANIMAL_INS
    )
WHERE RANK = 1
;